# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Water Distribution Systems
email: info@waterdistribution.systems
description: > # this means to ignore newlines until "baseurl:"
        Water Distribution Systems Group at DICAM, University of Bologna (Italy)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://waterdistribution.systems" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  people:
    output: true
  research:
    output: true
  articles:
    output: true
  software:
    output: true
  data:
    output: true

